version: "3.9"
services:
  client:
    build: Part2Python/.
    container_name: client
    depends_on:
      mysql-service:
        condition: service_healthy
        
  mysql-service:
    image: mysql:latest
    container_name: mysql-service
    volumes:
      - ./Part2Python/init.sql:/home/init.sql
    command: --init-file /home/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      
